export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
export const SET_SEARCHED_MOVIES = "SET_SEARCHED_MOVIES";
export const SET_MOVIE = "SET_MOVIE";
export const SET_ERROR = "SET_ERROR";
export const SET_IS_PENDING = "SET_IS_PENDING";
